### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by konklone**
Updates the frozen `node_modules` to the latest version of everything.

### CODE REVIEW

**Comment by konklone** [comment]
@divergentdave any idea why the build broke because of JS linting on HTML footers? https://travis-ci.org/konklone/oversight.io/builds/88698113

**Comment by divergentdave** [comment]
Starting from master and running `npm update ejs` results in the same set of errors, so it must be due to a difference in ejs template output. I'll take a look at what changed; I figure the solution will include turning off a different set of warnings.

**Comment by divergentdave** [comment]
It's passing now, the solution was indeed two other warnings. I did some further cleanup in the same file as well.

**Comment by konklone** [comment]
Thank you! I admit to being pretty new to EJS linting, and thought it was a JS checker failing on analyzing HTML, given some of the line numbers in the warnings. Much obliged.

**Pull request merged**
