### PR TITLE
Changed colors to blues

### PR DESCRIPTION
**Pull request by rebeccawilliams**
based on http://thenationalrealestatepost.com/wp-content/uploads/2014/02/financial-oversight-300x269.jpg + http://colorhunter.com/browse.php?h=y&p=http%3A%2F%2Fthenationalrealestatepost.com%2Fwp-content%2Fuploads%2F2014%2F02%2Ffinancial-oversight-300x269.jpg

### CODE REVIEW

**Comment by konklone** [comment]
As submitted:

oversight io bringing into sight the us government s oversight community

**Comment by rebeccawilliams** [comment]
a:visited could be brighter/lighter (classic traditional link color? #0000FF), but I think blues are a step in the right direction.

**Comment by konklone** [comment]
OK, you've motivated me to ditch the green. But I prefer brown:

brown

**Comment by rebeccawilliams** [comment]
Consider black?
screen shot 2015-01-27 at 2 17 40 am

**Comment by rebeccawilliams** [comment]
The links pop better on the black IMO. Maybe the issue all along is it was relying too much of one color.

**Pull request merged**
